/**
 * Created by bitholic on 2017/2/3.
 */

export const INC = 'INCREMENT';
export const DEC = 'DECREMENT';
export const TEXT_CHANGED = 'TEXT_CHANGED';
export const UPDATE_TEXT = 'UPDATE_TEXT';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';

export const NAVIGATION_TAB = 'NAVIGATION_TAB';
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';

export const INPUT_QUESTION = 'INPUT_QUESTION';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const FETCH_ANSWER = 'FETCH_ANSWER';
export const FETCH_ANSWER_PENDING = 'FETCH_ANSWER_PENDING';
export const FETCH_ANSWER_FULFILLED = 'FETCH_ANSWER_FULFILLED';
export const FETCH_ANSWER_REJECTED = 'FETCH_ANSWER_REJECTED';
