/**
 * Created by bitholic on 2017/2/3.
 */

export const INC = 'INCREMENT';
export const DEC = 'DECREMENT';
export const TEXT_CHANGED = 'TEXT_CHANGED';
export const UPDATE_TEXT = 'UPDATE_TEXT';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';

export const NAVIGATION_TAB = 'NAVIGATION_TAB';
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';

export const CHANGE_QUESTION = 'CHANGE_QUESTION';
export const GET_SEARCH_HELP = 'GET_SEARCH_HELP';
export const GET_SEARCH_HELP_PENDING = GET_SEARCH_HELP + '_PENDING';
export const GET_SEARCH_HELP_FULFILLED = GET_SEARCH_HELP + '_FULFILLED';
export const GET_SEARCH_HELP_REJECTED = GET_SEARCH_HELP + '_REJECTED';

export const START_INPUT_QUESTION = 'START_INPUT_QUESTION';
export const STOP_INPUT_QUESTION = 'STOP_INPUT_QUESTION';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const SUBMIT_QUESTION_PENDING = 'SUBMIT_QUESTION_PENDING';
export const SUBMIT_QUESTION_FULFILLED = 'SUBMIT_QUESTION_FULFILLED';
export const SUBMIT_QUESTION_REJECTED = 'SUBMIT_QUESTION_REJECTED';